name: Deploy

on:
  push:
    branches:
      - main

jobs:
  send_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .

      - name: Docker Login
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Push
        run: |
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}

      - name: Deploy to Portainer as a stack
        uses: portainer/portainer-action@v2
        with:
          endpoint: ${{ secrets.PORTAINER_ENDPOINT }}
          username: ${{ secrets.PORTAINER_USERNAME }}
          password: ${{ secrets.PORTAINER_PASSWORD }}
          stack: ${{ secrets.DOCKER_STACK_NAME }}
